CREATE TABLE usuarios (
	id INT NOT NULL AUTO_INCREMENT,
	nome VARCHAR(255) NOT NULL,
	email VARCHAR(100) NOT NULL UNIQUE,
	senha VARCHAR(150) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE tarefas(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	idUsuario INT NOT NULL REFERENCES tb_usuarios(id),
	descricao VARCHAR(255) NOT NULL,
	dtInicio DATE,
	dtFim DATE,
	status VARCHAR(50) NOT NULL
);